name: Secrets DEMO

on:
  push:   
  
  workflow_dispatch:

jobs:
  # Job Secrets
  uso-secrets:    
    runs-on: ubuntu-latest
    
    steps:
      - name: Usar el secret
        run: echo "Valor del token ${{secrets.API_TOKEN}}"

      - name: Usar el secret como una variable de entorno
        env:
          TOKEN: ${{secrets.API_TOKEN}}
        run: |
          echo "El token tiene $(echo -n "$TOKEN" | wc -c) caracteres"
          echo "Valor enmascarado: $TOKEN"
